### PR TITLE
Update screenshot

### LINKED ISSUE #90: Update Pixyll screenshot in the readme.

### PR DESCRIPTION
**Pull request by thedch**
Hi all --

Thought I'd take a swing at #90 -- not sure if this is what you had in mind.

Best,
Daniel

Fixes #90.

### CODE REVIEW

**Comment by ashawley** [comment]
Thanks for taking this on!  

I'm not sure what @johno had in mind for #90.  Maybe just updating is all it was?

**Comment by ashawley** [comment]
Could it be renamed screenshot.png and put it in the root directory?  That seems to be the convention for other Jekyll themes.

The file size is 372k.  That seems pretty large.  Maybe resizing it would make it smaller.

I wonder if there is a convention for this kind of thing with the Jekyll theme sites ([1](http://jekyllthemes.org/) [2](https://jekyllthemes.io) or for Jekyll themes generally?

**Comment by plttn** [comment]
Just ran the screenshot through TinyPNG and came up with something that is now 62KB. 
homepage 1

**Comment by johno** [comment]
Yep, exactly what I had in mind - updating it to the latest v2 and making retina-friendly. Thanks folks 💟! And yeah, let's optimize that puppy to shrink the dl size.

**Comment by thedch** [comment]
compressed + renamed + moved :)

**Comment by ashawley** [comment]
Can you squash the commits together?

We should avoid having the larger copy of the file in the repo history.

**Comment by thedch** [comment]
do you want to do a squash merge?

**Comment by ashawley** [comment]
Merged in 2ad5051.

**Comment by ashawley** [comment]
Thanks for doing this! 👍

**Pull request closed without merging**
