### PR TITLE
Add build GitHub action

### PR DESCRIPTION
**Pull request by ashawley**
This is just based on the Ruby action:

https://github.com/actions/starter-workflows/blob/d037e97/ci/ruby.yml

### CODE REVIEW

**Comment by ashawley** [comment]
This is the first installment of trying to solve #388.

**Comment by ashawley** [comment]
I suppose we could use the Jekyll action, but I'm pretty sure we need to have more control over the build than that going forward.  Maybe the Jekyll action could be used to deploy the gh-pages.

**Comment by ashawley** [comment]
It ran for this pull request:

https://github.com/johno/pixyll/pull/419/checks?check_run_id=511235667

**Comment by ashawley** [comment]
I'll follow-up, and see if caching may be able to make this run slightly faster:

https://github.com/actions/cache/blob/master/examples.md#ruby---bundler

**Comment by kosalanuwan** [comment]
@ashawley I tried a combination of what you did for the `build.yml` script and another GitHub Action `peaceiris/actions-gh-pages@v3`. It seemed to do the job, at least for this repo:
<https://github.com/kosalanuwan/bookworm/blob/master/.github/workflows/publish.yml>

Notes:
- The repo is a detached fork of Pixyll v2 and v3.
- `gh-pages` only contains the `_site` binaries and not a copy of the `master`

**Pull request merged**
