### PR TITLE
Build in Appveyor

### PR DESCRIPTION
**Pull request by ashawley**
Automated builds specifically on Windows may benefit those users.  Although, I predict it isn't necessary:  The entire stack (Ruby, bundler, Jekyll) should be so portable these days that it is of no concern.  

However, maybe there's a chance this is generally useful as a starting point to some users.  Appveyor would be the recommendation.  And a Windows build may be helpful should we run in to issues specific to Windows users with gem-based themes for #333 and #360.

Before merging this, @johno would need to [sign-in](https://ci.appveyor.com/login) at Appveyor and enable this repo.

### CODE REVIEW

**Comment by johno** [comment]
Awesome! I’ll put it on my todo list for this week.

**Comment by ashawley** [comment]
@johno Could you try enabling Appveyor for Pixyll, at some point?  Start here: https://ci.appveyor.com/login  If it works, then merge this branch.

**Comment by johno** [comment]
Done, thanks @ashawley

**Comment by ashawley** [comment]
Cool, thanks!  Did you see a build happen?  

I was expecting Appveyor would be running for pull requests or merges to master.  I'm looking here, https://ci.appveyor.com/project/johno/pixyll, but not seeing anything.

**Comment by johno** [comment]
Oh whoops, looks like I didn't fully add it. Should be g2g now https://ci.appveyor.com/project/johno/pixyll

**Comment by ashawley** [comment]
🚀 Looking good!  Awesome, thanks.

**Pull request merged**
